name: Go

on: [pull_request, workflow_dispatch]
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: go get ...
      run: |
        go get golang.org/x/lint/golint
        go get golang.org/x/tools/cmd/goimports
    - name: Docker Build
      run: make docker
    - name: Docker run
      run: docker run -t kafka-client help
    - name: Local Build (dependency of Test section)
      run: make mod build
    - name: Test
      run: make test
    
